# Generated by Django 5.1.4 on 2025-02-12 09:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobuybro', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='profile_photos/default.png', max_length=255, verbose_name='image'),
        ),
    ]
