# Generated by Django 5.1.4 on 2025-02-12 12:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobuybro', '0005_alter_post_video_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dytquc7fv/image/upload/v1739363352/xiunevpnqcxsoxb5mumq.png', max_length=255, verbose_name='profile_photo'),
        ),
    ]
